abp/protected/models/Equipos.php
<?php


class Equipos extends CActiveRecord
{
	
	
	
	public static function model($className=__CLASS__){
		
		return parent::model($className);
		
	}
		public function rules()
	{
		return array(
			array('nombre, direccion, telefono, tecnicos_Id', 'required', 'message'=>'campos requerido'),
		);
	}
	

}

abp/protected/models/Jugadores.php
<?php


class Jugadores extends CActiveRecord
{
	
	
	
	public static function model($className=__CLASS__){
		
		return parent::model($className);
		
	}
		public function rules()
	{
		return array(
			array('nombre,apellido,posicion,dorsal,equipo_id', 'required', 'message'=>'campos requeridos'),
		);
	}
	
	

}

abp/protected/models/Tecnicos.php
<?php


class Tecnicos extends CActiveRecord
{
	
	
	
	public static function model($className=__CLASS__){
		
		return parent::model($className);
		
	}
		public function rules()
	{
		return array(
			array('nombre, apellido', 'required', 'message'=>'campos requeridos'),
		);
	}
	
	

}

abp/protected/controllers/EquiposController.php
<?php
class EquiposController extends Controller
{
	public function actionIndex()
	{
	if(isset($_POST['Equipos'])){
	
		//rint_r($_POST['Cliente']);
		$guardar = new Equipos();
		$guardar->attributes = $_POST['Equipos'];
	//	print_r($guardar);
		if($guardar->save()){
			//echo "guardo!";
		}
	}
		$modelo = new Equipos();
		$this->render('index',array('modelo'=>$modelo));
	
	}
	public function actionMostrarEquipos(){
		
		//$modelo =  Equipos::model()->findAll();
		 $modelo = Yii::app()->db->createCommand('
		 SELECT equipos.id, equipos.nombre, equipos.direccion, equipos.telefono, tecnicos.nombre As Tecnico
		 FROM equipos
		 INNER JOIN tecnicos ON equipos.tecnicos_Id = tecnicos.Id')->queryAll();
		$this->render('mostrar',array('modelo'=>$modelo));
	}
	
	public function actionEditar($id){
		
	//	echo $id;
		
		$guardar = Equipos::model()->findByPk($id);
		if(isset($_POST['Equipos'])){
			$guardar->attributes = $_POST['Equipos'];
		
		if($guardar->save()){
			$this->redirect(array('mostrarEquipos'));
		}
	
	}

		$this->render('modificar',array('modelo'=>$guardar));

	}
	
	public function actionEliminar($id){
		try{
		$eliminar = Equipos::model()->findByPk($id);
		$eliminar->delete();
		$this->redirect(array('mostrarEquipos'));
		}catch(Exception $e){
			
			$this->redirect(array('mostrarEquipos'));
		}
	}
}

abp/protected/controllers/JugadoresController.php
<?php
class JugadoresController extends Controller
{
	public function actionIndex()
	{
	if(isset($_POST['Jugadores'])){
	
		//rint_r($_POST['Cliente']);
		$guardar = new Jugadores();
		$guardar->attributes = $_POST['Jugadores'];
	//	print_r($guardar);
		if($guardar->save()){
			//echo "guardo!";
		}
	}
		$modelo = new Jugadores();
		$this->render('index',array('modelo'=>$modelo));
	
	}
	public function actionMostrarJugadores(){
		
		//$modelo =  Equipos::model()->findAll();
		 $modelo = Yii::app()->db->createCommand('
		 SELECT jugadores.nombre,jugadores.posicion, jugadores.dorsal, jugadores.apellido, jugadores.Id, equipos.nombre As nombre_equipo
		FROM jugadores
		INNER JOIN equipos ON jugadores.equipo_id= equipos.id')->queryAll();
		$this->render('mostrar',array('modelo'=>$modelo));
	}
	
	public function actionEditar($id){
		
	//	echo $id;
		
		$guardar = Jugadores::model()->findByPk($id);
		if(isset($_POST['Jugadores'])){
			$guardar->attributes = $_POST['Jugadores'];
		
		if($guardar->save()){
			$this->redirect(array('mostrarJugadores'));
		}
	
	}

		$this->render('modificar',array('modelo'=>$guardar));

	}
	
	public function actionEliminar($id){
		try{
		$eliminar = Jugadores::model()->findByPk($id);
		$eliminar->delete();
		$this->redirect(array('mostrarJugadores'));
		}catch(Exception $e){
			
			$this->redirect(array('mostrarJugadores'));
		}
	}
}

abp/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

abp/protected/controllers/TecnicosController.php
<?php
class TecnicosController extends Controller
{
	public function actionIndex()
	{
	if(isset($_POST['Tecnicos'])){
	
		//rint_r($_POST['Cliente']);
		$guardar = new Tecnicos();
		$guardar->attributes = $_POST['Tecnicos'];
		//print_r($guardar);
		if($guardar->save()){
			echo "guardo!";
		}
	}
		$modelo = new Tecnicos();
		$this->render('index',array('modelo'=>$modelo));
	
	}
	
	public function actionMostrarTecnicos(){
		
		$modelo =  Tecnicos::model()->findAll();
		$this->render('mostrar',array('modelo'=>$modelo));
	}
	
	public function actionEditar($id){
		
		$guardar = Tecnicos::model()->findByPk($id);
		if(isset($_POST['Tecnicos'])){
			$guardar->attributes = $_POST['Tecnicos'];
		
		if($guardar->save()){
			$this->redirect(array('mostrarTecnicos'));
		}
	
	}

		$this->render('modificar',array('modelo'=>$guardar));

	}
	
	public function actionEliminar($id){
		try{
		$eliminar = Tecnicos::model()->findByPk($id);
		$eliminar->delete();
		$this->redirect(array('mostrarTecnicos'));
		}catch(Exception $e){
			
			$this->redirect(array('mostrarTecnicos'));
		}
	}
	



}

abp/protected/views/jugadores/index.php
<?php
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
));?>

<h3>Nuevo Jugador -  <?php echo CHtml::link('Gestionar Jugador',array('mostrarJugadores'));?></h3>
<table border>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'nombre');?></b></td>
<td><?php echo $form->textField($modelo,'nombre');?></td>
<td><?php echo $form->error($modelo,'nombre');?></td>
</div>
</tr>

<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'apellido');?></b></td>
<td><?php echo $form->textField($modelo,'apellido');?></td>
<td><?php echo $form->error($modelo,'apellido');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'posicion');?></b></td>
<td><?php echo $form->textField($modelo,'posicion');?></td>
<td><?php echo $form->error($modelo,'posicion');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'dorsal');?></b></td>
<td><?php echo $form->textField($modelo,'dorsal');?></td>
<td><?php echo $form->error($modelo,'dorsal');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'Equipo');?></b></td>
<td><?php echo CHtml::activeDropDownList($modelo, 'equipo_id', 
CHtml::listData(Equipos::model()->findAll(),'id', 'nombre')); ?></td>
<td><?php echo $form->error($modelo,'equipo_id');?></td>
</div>
</tr>

<div>
<tr>
<td>
<?php 
echo "<br>";
echo CHtml::submitButton('Guardar');?>
</td>
</tr>
</div>
</table>
<?php
$this->endWidget();
 ?>

abp/protected/views/jugadores/modificar.php
<?php
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
));?>

<h3>Modificando Jugador </h3>
<table border>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'nombre');?></b></td>
<td><?php echo $form->textField($modelo,'nombre');?></td>
<td><?php echo $form->error($modelo,'nombre');?></td>
</div>
</tr>

<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'apellido');?></b></td>
<td><?php echo $form->textField($modelo,'apellido');?></td>
<td><?php echo $form->error($modelo,'apellido');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'posicion');?></b></td>
<td><?php echo $form->textField($modelo,'posicion');?></td>
<td><?php echo $form->error($modelo,'posicion');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'dorsal');?></b></td>
<td><?php echo $form->textField($modelo,'dorsal');?></td>
<td><?php echo $form->error($modelo,'dorsal');?></td>
</div>
</tr>
<tr>
<div>
<td><b><?php echo $form->labelEx($modelo,'Equipo');?></b></td>
<td><?php echo CHtml::activeDropDownList($modelo, 'equipo_id', 
CHtml::listData(Equipos::model()->findAll(),'id', 'nombre')); ?></td>
<td><?php echo $form->error($modelo,'equipo_id');?></td>
</div>
</tr>

<div>
<tr>
<td>
<?php 
echo "<br>";
echo CHtml::submitButton('Guardar');?>
</td>
</tr>
</div>
</table>
<?php
$this->endWidget();
 ?>

abp/protected/views/jugadores/mostrar.php
<h1> Jugadores en el sistema </h1>
<table>
<tr>
	<th>Nombre</th>
	<th>Apellido</th>
	<th>Posicion</th>
	<th>Dorsal</th>
	<th>Equipo</th>
	<th>Opciones</th>
	
</tr>
<tr>
<?php 

foreach($modelo as $v){?>
<tr>
	<td><?php echo $v['nombre'] ?></td>
	<td><?php echo $v['apellido'] ?></td>
	<td><?php echo $v['posicion'] ?></td>
	<td><?php echo $v['dorsal'] ?></td>
	<td><?php echo $v['nombre_equipo']?></td>
	<td><?php echo CHtml::link('Editar',array('editar','id'=>$v['Id']));?>
		<?php echo CHtml::link('Eliminar',array('eliminar','id'=>$v['Id']),array('confirm'=>"Esta seguro que desea eliminar a este cliente?"));?>
	</td>
</tr>
<?php }?>
</tr>
</table>

abp/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

abp/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

abp/protected/views/layouts/main.php
<?php /* @var $this Controller */ 
?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">
	
	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Nuevo Tecnico ', 'url'=>array('/tecnicos/index'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Nuevo Equipo ', 'url'=>array('/equipos/index'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Nuevo Jugador', 'url'=>array('/jugadores/index'), 'visible'=>Yii::app()->user->isGuest)

	
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

abp/protected/views/site/pages/about.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name . ' - About';
$this->breadcrumbs=array(
	'About',
);
?>
<h1>About</h1>

<p>This is a "static" page. You may change the content of this page
by updating the file <code><?php echo __FILE__; ?></code>.</p>